#!/syestem/(nama admin)/echo/bash/sh
echo"hai apakabar
//pasti baik kan
echo*
break"*

loop"kamu pasti bingung mengapa aku buat ini
echo"/jadi sebenarnya gini...
echo"aku tu udah lama suka sama kamu
echo"tapi aku ga bisa ngungkapin perasaanku kpd kamu
bin.sh

#!/syestem2/(nama admin)/break/io
echo"intinya gini kamu mau ga jadi pacar aku?
                                          "break"
>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<                                          
